from pathlib import Path

PROJECT_ROOT = Path(__file__).parent

BOARD_WIDTH = 40
BOARD_HEIGHT = 30
PADDLE_HEIGHT = 4

SHOW_DETECTIONS = False

USE_OPTIMAL_AI = False

TRACKED_POSITIONS_COUNT = 30

SKIN_LOWER_BOUND = (0, 48, 80)
SKIN_UPPER_BOUND = (20, 255, 255)
